spring:
  application:
    name: movement
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: demo

server:
  port: 8087

microservices:
  customer:
    urlPaths:
      getCustomerById: http://localhost:8081/api/customers/{customerId}
  account:
    urlPaths:
      getAccountByNumber: http://localhost:8083/api/accounts/{accountNumber}
      putAccount: http://localhost:8083/api/accounts/{accountId}
  credit:
    urlPaths:
      getCreditByNumber: http://localhost:8085/api/credits/{accountNumber}
      getCreditByCustomerDocument: http://localhost:8085/api/credits
      putCredit: http://localhost:8085/api/credits/{creditId}
  debitCards:
    urlPaths:
      getDebitCards: http://localhost:8084/api/debitCards
  creditCards:
    urlPaths:
      getCreditCards: http://localhost:8086/api/creditCards